import logging
from app.graph.state import SearchState

logger = logging.getLogger(__name__)

class CitationValidationAgent:
    """
    Validates that all citations generated by the Answer Generation Agent
    actually correspond to retrieved and verified URLs.
    """
    def validate(self, state: SearchState) -> SearchState:
        state["execution_trace"].append("citation_validation")
        
        citations = state.get("citations", [])
        if not citations:
            return state
            
        selected_sources = state.get("selected_sources", [])
        valid_urls = {s.get("url") for s in selected_sources}
        valid_ids = {str(s.get("id", "")) for s in selected_sources}
        valid_ids.update({str(s.get("url", "")) for s in selected_sources})
        
        validated_citations = []
        invalid_count = 0
        
        for cit in citations:
            url = cit.get("url")
            source_id = str(cit.get("source_id"))
            
            # Check if the citation matches any valid source ID or URL
            is_valid = (url in valid_urls) or (source_id in valid_ids)
            
            if is_valid:
                validated_citations.append(cit)
            else:
                invalid_count += 1
                logger.warning(f"Removed fabricated citation: {url} (ID: {source_id})")
                
        state["citations"] = validated_citations
        
        if invalid_count > 0:
            state["warnings"].append(f"Removed {invalid_count} invalid or fabricated citation(s).")
            
        return state
