from typing import Type, TypeVar, Optional
import json
from pydantic import BaseModel
from app.llm.base import LLMProvider

T = TypeVar('T', bound=BaseModel)

class MockLLMProvider(LLMProvider):
    """
    A deterministic Mock LLM for offline testing and development.
    It returns hardcoded responses based on query keywords or schema requirements.
    """
    
    def generate(self, prompt: str, system_prompt: Optional[str] = None) -> str:
        prompt_lower = prompt.lower()
        if "conflict" in prompt_lower or "disagree" in prompt_lower:
            return "Sources disagree on this point. Source A claims X, while Source B claims Y."
        return "This is a deterministic mock response based on retrieved evidence."
        
    def generate_structured(self, prompt: str, output_schema: Type[T], system_prompt: Optional[str] = None) -> T:
        prompt_lower = prompt.lower()
        
        # 1. Planner Mocks
        if output_schema.__name__ == "SearchPlan":
            if "compare" in prompt_lower or "vs" in prompt_lower:
                intent = "comparison"
                verification = True
                sources = 3
                reasoning = True
            elif "latest" in prompt_lower or "today" in prompt_lower:
                intent = "freshness"
                verification = True
                sources = 2
                reasoning = False
            else:
                intent = "factual"
                verification = True
                sources = 2
                reasoning = False
                
            return output_schema(
                intent=intent,
                sub_queries=[prompt],
                search_modes=["hybrid"],
                verification_required=verification,
                max_sources=sources,
                reasoning_required=reasoning,
                freshness_required=(intent == "freshness")
            )
            
        # 2. Verification Mocks
        elif output_schema.__name__ == "VerificationResult":
            # If the prompt explicitly tests insufficient evidence
            if "insufficient" in prompt_lower and "evidence" in prompt_lower:
                return output_schema(
                    source_id="mock_id",
                    relevant=False,
                    supports_query=False,
                    evidence_quality=0.0,
                    notes=["Insufficient evidence to support query."]
                )
            
            # Default to supporting
            return output_schema(
                source_id="mock_id",
                relevant=True,
                supports_query=True,
                evidence_quality=0.9,
                notes=["Source is relevant and supports the query."]
            )
            
        # 3. Evidence Extraction Mocks
        elif output_schema.__name__ == "EvidenceList":
            # Very basic extraction mock
            return output_schema(
                claims=[{
                    "claim": "Mocked claim extracted from text.",
                    "source_id": "mock_id",
                    "url": "https://example.com",
                    "support_level": "strong",
                    "evidence_text": "Snippet of text.",
                    "confidence": 90
                }]
            )
            
        # 4. Conflict Detection Mocks
        elif output_schema.__name__ == "ConflictResult":
            if "100" in prompt and "120" in prompt:
                return output_schema(
                    conflict_detected=True,
                    conflict_details="Sources disagree: Source A says 100, Source B says 120."
                )
            return output_schema(conflict_detected=False, conflict_details=None)
            
        # 5. Reasoning Mocks
        elif output_schema.__name__ == "ReasoningSummary":
            return output_schema(
                reasoning_summary="Based on the retrieved sources, the evidence strongly supports the answer."
            )
            
        # 6. Answer Mocks
        elif output_schema.__name__ == "AnswerResult":
            if "insufficient" in prompt_lower:
                return output_schema(
                    answer="The available evidence is insufficient for a definitive conclusion.",
                    citations=[],
                    confidence=10
                )
                
            return output_schema(
                answer="This is a deterministic, evidence-based answer generated by the Mock LLM.",
                citations=[{
                    "citation_id": "S1",
                    "source_id": "mock_id",
                    "url": "https://example.com",
                    "title": "Mock Title"
                }],
                confidence=95
            )

        # Fallback to an empty instance if possible, or raise error
        try:
            return output_schema()
        except:
            raise ValueError(f"MockLLMProvider does not know how to mock {output_schema.__name__}")
